message_do_not_modify: Do not edit this file, this is handled by Salt
empty_state:
  cmd.run:
    - name: echo 'empty state'
    - unless: True

events:
  - 'salt/netapi/hook/marathon/events':
      - salt://haproxy/kick_service.sls
      - salt://riemann/kick_service.sls

java:
  version: 8
  flavor: oracle
  share_dir: /usr/share/java
