message_do_not_modify: Do not edit this file, this is handled by Salt
empty_state:
  cmd.run:
    - name: echo 'empty state'
    - unless: True

events:
  - 'salt/netapi/hook/marathon/events':
      - salt://reactor/sync_services.sls

java:
  version: 8
  flavor: oracle
